resourcestring
//Dialogs
  rcErrPrepareNode = 'Ошибка обработки узла %s';
  rcErrCompNodes = 'Узел не является узлом %s';
  rcErrWriteNode = 'Ошибка записи данных для узла %s';
  rcErrReadNode = 'Ошибка чтения данных из узла %s';
  rcErrMissValue = 'Недопустимое значение атрибута для узла %s';
  rcErrMissAgrument = 'Недопустимый аргумент в вызове функции';
  rcUnUsedTag = 'Неучтенный тэг ';
  rcDuplicateLink = 'Такая ссылка уже есть в списке';
  rcWrongAttr = 'Неверное значение атрибута %s';
  rcRightAttrValues = 'Допустимые значения атрибута: %s';
  rcErrCGroupCreate ='Пустой XML-документ. Чтение групп контактов прервано';
  rcErrNullAuth = 'Параметр Auth не может быть пустым';
  rcErrFileName = 'Файл %s отсутствует';
  rcErrFileNull = 'Не задан файл по умолчанию';
//Variables
